[
  { id: "5GS107C4MB", title: "acquiring", sets: verbsAcquiring },
  { id: "WD17IU2G43", title: "analyzing", sets: verbsAnalyzing },
  {
    id: "M6XRL2D850",
    title: "artistic creation",
    sets: verbsArtisticCreation,
  },
  { id: "BFU0N2C897", title: "conditions", sets: verbsConditions },
  { id: "D8JSF34Q60", title: "conflicts", sets: verbsConflicts },
  { id: "PMEBG23987", title: "controlling", sets: verbsControlling },
  { id: "H0K743EQ8B", title: "cooperation", sets: verbsCooperation },
  { id: "JN951PKX67", title: "daily activities", sets: verbsDailyActivities },
  {
    id: "G7LR98IE32",
    title: "decaying and declining",
    sets: verbsDecayingAndDeclining,
  },
  { id: "W68CZ079DY", title: "deciding", sets: verbsDeciding },
  { id: "84Y05EU6IO", title: "existence", sets: verbsExistence },
  {
    id: "YR402FG6U9",
    title: "growth and development",
    sets: verbsGrowthAndDevelopment,
  },
  { id: "1EH5LZ9A80", title: "handling", sets: verbsHandling },
  { id: "62WP0YRX45", title: "health", sets: verbsHealth },
  { id: "OG0VLH9258", title: "hearing", sets: verbsHearing },
  { id: "YE9M4P0L17", title: "locomotion", sets: verbsLocomotion },
  { id: "1RT630E7ZN", title: "losing", sets: verbsLosing },
  { id: "6U21A95QMS", title: "making", sets: verbsMaking },
  { id: "7ZO96W34YK", title: "manipulating", sets: verbsManipulating },
  { id: "6OSV9H358I", title: "navigation", sets: verbsNavigation },
  {
    id: "2K1E06C9SO",
    title: "negative emotions",
    sets: verbsNegativeEmotions,
  },
  { id: "XKZ1503S6Y", title: "neutral emotions", sets: verbsNeutralEmotions },
  {
    id: "OL15Y0G3R8",
    title: "non verbal communication",
    sets: verbsNonVerbalCommunication,
  },
  { id: "B0M48XOS52", title: "owning", sets: verbsOwning },
  { id: "XSJZ714W82", title: "physical actions", sets: verbsPhysicalActions },
  { id: "BRY3M871J9", title: "planning", sets: verbsPlanning },
  {
    id: "OV0YGJ5317",
    title: "positive emotions",
    sets: verbsPositiveEmotions,
  },
  { id: "W052NLYJ96", title: "relationships", sets: verbsRelationships },
  { id: "YDHS637T51", title: "remembering", sets: verbsRemembering },
  { id: "70ZW964SIU", title: "seeing", sets: verbsSeeing },
  {
    id: "97R1V8FY2D",
    title: "sports and exercise",
    sets: verbsSportsAndExercise,
  },
  { id: "TE3P81MV69", title: "thinking", sets: verbsThinking },
  { id: "UJZ7EO1893", title: "touching", sets: verbsTouching },
  { id: "DZ6W8TR529", title: "transformations", sets: verbsTransformations },
  { id: "GPF14UW789", title: "transport", sets: verbsTransport },
  { id: "R014Z5YO6I", title: "understanding", sets: verbsUnderstanding },
  {
    id: "6W095BY7CD",
    title: "verbal communication",
    sets: verbsVerbalCommunication,
  },
  { id: "AHL5CM6240", title: "writing", sets: verbsWriting },
  {
    id: "7F03RA4OP2",
    title: "written communication",
    sets: verbsWrittenCommunication,
  },
];
